#include "ChartWindow.h"

// autogenerated by Qt
#include "./src/ui_ChartWindow.h"

//*****************************************************************************

void ChartWindow::displayChart(QString seriesTitle,
                               QString chartTitle,
                               initializerQString categoryTitles,
                               initializerDouble values,
                               double min,
                               double max) const
{
  // 1 set
  QBarSet *set = new QBarSet(seriesTitle);

  for (auto value : values) *set << value;

  // 1 set -> 1 series
  QBarSeries *series = new QBarSeries();
  series->append(set);

  // bars series
  series->setLabelsVisible(true);

  // 1 set -> 1 series -> 1 chart
  QChart *chart = new QChart();
  chart->addSeries(series);
  chart->setTitle(chartTitle);
  chart->setAnimationOptions(QChart::SeriesAnimations);

  QStringList categories { categoryTitles };
  QBarCategoryAxis *axisX = new QBarCategoryAxis();
  axisX->append(categories);

  QValueAxis *axisY = new QValueAxis;
  axisY->setRange(min, max);

  chart->addAxis(axisX, Qt::AlignBottom);
  chart->addAxis(axisY, Qt::AlignLeft);
  series->attachAxis(axisX);
  series->attachAxis(axisY);

  QChartView *chartView = new QChartView(chart);
  chartView->setRenderHint(QPainter::Antialiasing);

  // adding to: Frame object
  // placeholder Widget in ui
  QLayout *layout = this->ui->chartLayout->layout();
  if (layout != nullptr) layout->addWidget(chartView);
}

//*****************************************************************************

ChartWindow::ChartWindow(QString seriesTitle,
                         QString chartTitle,
                         initializerQString categoryTitles,
                         initializerDouble values,
                         double min,
                         double max,
                         QWidget *parent)
  : QWidget(parent)
  , ui(new Ui::ChartWindow)
{
  ui->setupUi(this);

  this->resize(values.size() * 320, 480);

  displayChart(seriesTitle, chartTitle, categoryTitles, values, min, max);
}

//*****************************************************************************

ChartWindow::~ChartWindow()
{
  delete ui;
}
